export const EXAMPLE_ACTION = 'EXAMPLE_ACTION';
export const EXAMPLE_ANOTHER_ACTION = 'EXAMPLE_ANOTHER_ACTION';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
